### PR TITLE
Create pl.json

### PR DESCRIPTION
**Pull request by jonostanck**
Polish language

# Description

Translation into Polish.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by fratsloos** [comment]
@jonostanck Thank you for the translation. Unfortunately I'm having some trouble getting the development environment to work. I'll try this again at a later time and if it works I'll merge your PR.

**Review by fratsloos — APPROVED** [review]
Tab settings in the file are not correct, but I'll fix that when the code is merged to the project.

**Comment by jonostanck** [comment]
Thanks and sorry I missed that.

**Comment by fratsloos** [comment]
No problem. :) I'm already glad you took the time to translate the file!

**Comment by jonostanck** [comment]
@fratsloos
I'm so glad I could be the catalyst for updating this great card! It works perfectly and finally in my native language :)
Thanks for making my dream dashboard possible :)
image

**Comment by BrettEBowman** [comment]
@jonostanck What are you using to get get the Radar/map display?

**Comment by jonostanck** [comment]
@BrettEBowman ADS-B Exchange's map via simple iframe with a little card_mod hack to hide Copyright at the bottom:
```
      - type: iframe
        url: >-
          https://globe.adsbexchange.com/?hideSidebar&hideButtons&tempTrails=240&mapDim=0&zoom=11&lat=51.34&lon=20.34
        aspect_ratio: 120%
        card_mod:
          style:
            .: |
              ha-card #root {
                margin-bottom: -40px;
              }
```

**Comment by fratsloos** [comment]
> @fratsloos I'm so glad I could be the catalyst for updating this great card! It works perfectly and finally in my native language :) Thanks for making my dream dashboard possible :)
That's a very nice dashboard! Would be nice if you could filter the data on the map with your own radar using an extra GET-var.

**Pull request merged**
